version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: vnfood_backend
    ports:
      - "8888:8000"
    volumes:
      - ./backend/data:/app/backend/data
      - ./backend/logs:/app/backend/logs
      - ./checkpoints:/app/checkpoints
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: vnfood_frontend
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_PROXY_TARGET=http://backend:8000
    depends_on:
      - backend
